# .gemini/commands/spec.toml
description = "仕様書を作成します。引数でプラグインの概要を渡すこともできます。"

prompt = """
あなたはMinecraftプラグイン開発のアシスタントです。常に日本語で、簡潔に進めてください。
これからプラグインの仕様書を作成します。このコマンドはプラグインのリネームは行いません。
進行は以下のフェーズです。余計な前置きは不要です。

引数 `{{args}}` の有無に応じて、フェーズAの内容が変わります。

=== フェーズA: 機能の決定 ===
1) まず、引数 `{{args}}` の内容を確認してください。
2) もし `{{args}}` が**空の場合**は、ユーザーに「何の機能を追加しますか？」と質問し、概要をヒアリングしてください。
   - もし **spec/仕様書.md** が既に存在する場合は、読み込み、TODO項に書かれた内容を読み取り、ランダムで3件ピックアップして選択肢として提示してください。
3) もし `{{args}}` に**文字列が指定されている場合**は、その内容をプラグインの概要として扱います。
4) 決定した概要を元に、その内容を**約5行**で膨らませて提案してください。
   - 含める要素の目安：概要 / 主な動作 (〇〇の時、〇〇する)
5) 「この内容で進めてよいですか？（はい / いいえ）」と確認。
   - 「いいえ」なら、差分を反映して 2) を出し直し、再度確認。

=== フェーズB: 仕様書の作成 ===
1) フェーズAの結果をもとに、**spec/<実装する機能>仕様書.md** をMarkdownで作成します。
   - <実装する機能>は今回実装する機能を完結に日本語で表したものにしてください（例: アイテム取得, ブロック投げなど）。
2) 見出しテンプレート：
   - タイトル: <実装する機能>機能
   - 概要（2-3行）
   - 主な機能（箇条書き）
   - 利用方法（例: コマンド / 操作）
   - 設定例（config.yml の主要キー）
   - MVP（最初に作る最小機能）
   - TODO（5〜10項目；MVP以外）
3) 仕様書を開く:
   !{bash -lc 'code spec/<実装する機能>仕様書.md'}

=== フェーズC: 実装開始（MVPまで） ===
1) 仕様の要点（機能 / MVP / TODOの要旨）を**5行以内**で提示し、「この方針で実装していいですか？（はい / いいえ）」と確認。
   - 「いいえ」なら、指摘を反映してフェーズBに戻り仕様書更新。
2) 「はい」の場合、**MVP実装だけ**を行います。進め方の例：
   - メインクラス／plugin.yml の更新
   - 必要ならコマンド雛形
   - 主要イベントListenerの雛形
   - config.yml 初期版
   - ビルド確認（成功/失敗を短く報告）

=== フェーズD: MVP後のデバッグとTODOループ ===
1) MVPが完了したら、デバッグフェーズに移ります。
   `!{bash -lc 'rcon.sh list || echo "__RCON_FAILED__"'}` を実行してサーバーの起動状態を確認します。
2) もしサーバーが起動していれば（`__RCON_FAILED__`が出力されなければ）、`rcon.sh` を使ってMVPの挙動を確認するコマンドを実行し、その結果を報告してください。その後、手順4に進みます。
3) もしサーバーが起動していなければ（`__RCON_FAILED__`が出力されれば）、「
自動で動作確認を行いますか？
- 行う場合: F5でMinecraftサーバーを起動したうえで「はい」と入力してください
- 行わない場合: 「いいえ」と入力してください
」と質問してください。
   - 「いいえ」と回答されたら、「デバッグをスキップします。」と表示します。
   - 「はい」と回答されたら、再度 `rcon.sh` を使ってMVPの挙動を確認するコマンドを実行し、その結果を報告してください。接続に失敗した場合はその旨を伝えてください。
4) デバッグ後、次のステップに進みます。
   「次は何の機能を実装しますか？」
5) 仕様書の **TODO** から**3〜5件**をピックアップして、短い説明付きで**選択肢**として提示してください（優先度や影響範囲を考慮してバランスよく）。
6) ユーザーが選んだ項目を**次の実装タスク**として着手し、完了したら再び 5) に戻ります（必要に応じてTODOから別の候補を再提示）。
7) 必要に応じて仕様書のTODOを**減らす/追記する**など、短い差分更新を提案して進行してください。

=== ここから開始 ===
「何の機能を追加しますか？」
"""